---
title: "`r params$title`"
output: 
  html_document:
    theme: null
    self_contained: false
params:
  file_path: 'I:/.shortcut-targets-by-id/15QBAXOC5TdfNgOtQZh2jvqN37NjxkSM0/@BICI/06_Eixo Dados/Projetos/Papo de pedal/Edicao 071124/result/pesquisa_papo_pedal.rds'
  title: 'Edição 07/11/2024'
includes:
  in_header:
    style.css
    actions.js
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning = FALSE,message = FALSE)
library(tidyverse)
library(data.table)
library(plotly)
library(leaflet)
library(htmltools)
library(htmlwidgets)

html_wrap <- function(x,w){
  s <- str_wrap(x,w)
  str_replace_all(s,"\\n","<br/>") %>% HTML() %>% 
    return()
}

html_single_wrap <- function(x,w){
  s <- str_wrap(x,w)
  sapply(s, function(s){
    str_replace(s,"\\n","<br>") %>% 
    str_replace_all("\\n"," ") %>% 
    HTML()
  }) %>% return()
}


```




```{r data, warning=FALSE,message=FALSE}

df <- readRDS(params$file_path)

description <- params$file_path %>% 
  dirname() %>% dirname() %>% 
  paste0("/description.txt") %>% 
  fread()

```


<div class="fullcontainer" style="width:100%;display:flex;position:relative;
flex-wrap:wrap;gap:0px;">

<style>
h1.title.toc-ignore{
  visibility: hidden;
  height: 0px;
  width: 0px;
  margin: 0;
}
html{overflow-y:hidden;}
h1,h2,h3,h4{
  font-family: Montserrat;
  color: #414042;
}
g.g-gtitle>text{
  font-family:Montserrat !important;
  fill: #414042 !important;
  font-weight: bold !important;
}
table.sinistros>tbody>tr>td{
  vertical-align: middle;
  text-align: center;
}
</style>

<div class="leftcol_top" style="width:29%;flex: 3 1 250px; position:relative;display:block;">

```{r whitediv, warning=FALSE,message=FALSE}

tags$div(style = "width:100%;min-height:60px;display:block;background-color:white")


```


```{r idade,  warning=FALSE,message=FALSE}

p <- df %>% 
  select(idade) %>% 
  mutate(idade = as.numeric(idade)) %>% 
  filter(!is.na(idade)) %>% 
  filter(idade!='') %>% 
  mutate(Idade_lbl = cut(idade,c(seq(0,80,10),100))) %>% 
  group_by(Idade_lbl) %>% 
  reframe(n = n()) %>% 
  mutate(perc = scales::percent(n/sum(n),.1)) %>% 
  plot_ly(
    x = ~Idade_lbl,
    y = ~n,
    type = "bar",
    text = ~perc,
    name = "Idade dos respondentes",
    marker = list(
      color = "#009889",
      line = list(color = "#325565",width = 1)
    )
  ) %>% 
  layout(
    title = "Idade dos respondentes",
    xaxis = list(title = "Idade"),
    yaxis = list(title = "Contagem")
  )

tags$div(
  style = "position:relative; width:100%;",
  p
)

```

</div>

<div class="rightcol_top" style="width:70%;flex: 6 1 600px; position:relative;display:flex;">

```{r motivo_escolha,  warning=FALSE,message=FALSE}

df2 <- df %>% 
  pull(por_que_escolheu_ou_escolhe_andar_de_bicicleta_agrupado) %>% 
  str_split(';') %>% 
  unlist() %>% 
  str_trim() %>% 
  table() %>% 
  as_tibble() %>% 
  setNames(c('value','n')) %>% 
  mutate(base = 2) %>% 
  arrange(-n) %>% 
  mutate(theta = seq(0,360,trunc(360/n()))[1:n()]) %>% 
  mutate(perc = scales::percent(n/sum(n),.1))

p <- plot_ly(
    data = df2,
    type = "barpolar",
    visible = TRUE,
    r = ~n,
    theta = ~theta,
    base = ~base,
    marker = list(
      color = "#00A0DC",
      line = list(color = "white", width = 2)
    ),
    hovertemplate = "%{text}: %{r}<extra></extra>",
    text = ~value
  ) %>% 
  layout(
    showlegend = FALSE,
    title = "Motivo da escolha da bicicleta",
    polar = list(
      angularaxis = list(
        tickvals = df2$theta,
        tickmode = "array",
        ticktext = str_wrap(df2$value,13),
        tickfont = list(
          family = "Montserrat",
          color = 'black'
        ),
        rotation = 90,
        gridcolor = '#e0e0e0',
        showline = F
      ),
      radialaxis = list(visible = FALSE)
    ),
    margin = list(l = 90, r = 90, t = 90, b = 70)
  )

tags$div(
  style = "position:relative; width:55%;",
  p
)

```


```{r problemas,  warning=FALSE,message=FALSE}

try({
  df <- df %>% 
    rename("qual_e_o_principal_problema_que_voce_enfrenta_ao_andar_de_bicicleta_em_fortaleza_agrupado"="qual_e_o_principal_problema_que_voce_enfrenta_ao_pedalar_em_fortaleza_agrupado")
})

p <- df %>% 
  pull(qual_e_o_principal_problema_que_voce_enfrenta_ao_andar_de_bicicleta_em_fortaleza_agrupado) %>% 
  str_split(";") %>% 
  unlist() %>% 
  str_trim() %>% 
  str_split(",") %>% 
  unlist() %>% 
  str_trim() %>% 
  table() %>% 
  as_tibble() %>% 
  setNames(c("value","n")) %>% 
  mutate(perc = n/sum(n)) %>% 
  arrange(-n)

if(any(p$perc<0.02)){
  p <- p %>% 
    filter(perc>=0.02)
  p <- bind_rows(
    p,
    tibble(
      value = "Outros",
      perc = 1-sum(p$perc)
    )
  )
}

p <- apply(p, 1, function(x){
  perc <- as.numeric(x["perc"])
  tags$div(
    class = "kpi",
    style = paste0("--p:",trunc(perc*100),";",
                   "--c:#F15A22;"),
    tags$div(
      class = "donut",
      `data-label`=html_wrap(x["value"],20),
      `data-value`=percent(perc,.1),
      tags$span(
        scales::percent(perc,.1)
      ),
      tags$div(
        class = "lbl",
        style = ifelse(str_width(x["value"])<40,"font-size:11px;",""),
        x["value"]
      )
    )
  )
})

#s <- HTML(read_lines("../css/style_donut.css")) %>% tags$style()

tags$div(
  style = "position:relative; width:45%;",
  tags$h4("Principal problema enfrentado"),
  tags$div(
    class = "grid",
    p,
    tags$link(href = "../../css/style_donut.css",rel = "stylesheet"),
    #s,
    tags$script(HTML(read_lines("../js/popup_donut.js")))
  )
)

```

</div>

</div>


<div class="fullcontainer" style="width:99vw;display:flex;position:relative;">


<div class="leftcol_bottom" style="width:70%;flex: 6 1 600px; position:relative;display:flex;">

```{r leafletmap, warning=FALSE,message=FALSE}

tags$div(
  style = "width:100%;height:500px;",
  tags$iframe(
    src = "../../basemap/map.html",
    style = "width:100%;height:100%;border:none;",
    id = "leafmap_edicoes",
    loading = "lazy"
  ),
  tags$script(
      readChar("../js/show_group.js",nchars = 9000) %>% 
        str_replace_all("GRUPO_ID",
                        as.character(description$data)) %>% 
        str_replace("LONGITUDE",as.character(description$long)) %>% 
        str_replace("LATITUDE",as.character(description$lat))
    )
)


```



</div>

<div class="rightcol_bottom" style="width:29%;flex: 3 1 250px; position:relative;display:block;">

```{r sinistros, warning=FALSE,message=FALSE}

if("voce_sofreu_acidente_ultimos_anos" %in% names(df) &
   "voce_tem_medo_de_acidente_andando_de_bicicleta_em_fortaleza" %in%  names(df)){
  
  tags$div(
  class = "sinistros",
  tags$img(
    src = "../css/noun-fear.svg"
  ),
  
)
  
}else{
  
  if("voce_tem_medo_de_acidente_andando_de_bicicleta_em_fortaleza" %in% names(df)){
    resp <- df$voce_tem_medo_de_acidente_andando_de_bicicleta_em_fortaleza
    resp <- resp[resp!=""] %>% na.exclude()
    
    tags$table(
      class = "sinistros",style="max-height:100px;",
      tags$tr(
        tags$td(style="width:25%;"),
        tags$td(
          tags$img(
            src = "../../css/noun-fear.svg",
            width  = "80%"
          )
        ),
        tags$td(
          tags$p(
            paste0(
              scales::percent(sum(str_detect(resp,
                                          "Sim|sim|SIM"))/length(resp)),
              " tem medo de acidentes"
            )
          )
        ),
        tags$td(style="width:25%;")
      )
    )
    
  }else{
    tags$div(class = "sinistros")
  }
  
}



```


```{r mudanca_modo, warning=FALSE,message=FALSE}

try({
  df <- df %>% 
    rename(
      "voce_gostaria_de_trocar_a_bicicleta_por_outro_meio_de_transporte_agrupado"="gostaria_de_trocar_a_bicicleta_por_outro_meio_de_transporte_agrupado"
    )
})


p <- df %>% 
  pull(voce_gostaria_de_trocar_a_bicicleta_por_outro_meio_de_transporte_agrupado) %>% 
  table() %>% 
  as_tibble() %>% 
  setNames(c("value","n")) %>% 
  arrange(-n) %>% 
  mutate(Percentual = scales::percent(n/sum(n)),.1) %>% 
  mutate(
    x = rep(1:3,n())[1:n()],
    y = sapply(ceiling(n()/3):1, rep,times = 3)[1:n()]
  ) %>% 
  mutate(norm_n = (100*(n/sum(n))) %>% ifelse(.<15,15,.)) %>% 
  mutate(value = html_single_wrap(value,15))

p <- plot_ly(
  data = p,
  x = ~x,
  y = ~y,
  text = ~paste0(value,"<br>",Percentual,"<br>"),
  hoverinfo = "text",
  textposition = "bottom center",
  type = 'scatter', mode = 'markers+text',
  marker = list(size = ~norm_n, opacity = 0.5)
) %>% 
  layout(title = 'Você gostaria de trocar a bicicleta\npor outro meio de transporte?',
         xaxis = list(showgrid = FALSE, visible = F),
         yaxis = list(showgrid = FALSE, visible = F,
                      range = c(0,max(p$y)+0.5)),
         margin = list(b = 60,t = 70,r = 10, l = 10))

tags$div(
  style = "width:100%",
  p
)


```

</div>


</div>